# Generated by Django 5.2.4 on 2025-08-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
