# Generated by Django 5.2.4 on 2025-08-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
