# Generated by Django 5.2.4 on 2025-08-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_ticket_price_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
